/** Built-in place names for profile suggestions. Local only: nothing is looked up online. */

export const COUNTRY_CODES: ReadonlyArray<[string, string]> = [
  ['+91', 'India'],
  ['+1', 'USA / Canada'],
  ['+44', 'United Kingdom'],
  ['+971', 'UAE'],
  ['+65', 'Singapore'],
  ['+61', 'Australia'],
  ['+49', 'Germany'],
  ['+966', 'Saudi Arabia'],
  ['+974', 'Qatar'],
  ['+977', 'Nepal'],
  ['+880', 'Bangladesh'],
  ['+94', 'Sri Lanka'],
];

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

/** City → state. Choosing a city suggestion also fills the state and country. */
export const INDIAN_CITIES: ReadonlyArray<[string, string]> = [
  ['Bengaluru', 'Karnataka'],
  ['Mysuru', 'Karnataka'],
  ['Mangaluru', 'Karnataka'],
  ['Hubballi', 'Karnataka'],
  ['Belagavi', 'Karnataka'],
  ['Davanagere', 'Karnataka'],
  ['Shivamogga', 'Karnataka'],
  ['Tumakuru', 'Karnataka'],
  ['Kalaburagi', 'Karnataka'],
  ['Udupi', 'Karnataka'],
  ['Mumbai', 'Maharashtra'],
  ['Pune', 'Maharashtra'],
  ['Nagpur', 'Maharashtra'],
  ['Nashik', 'Maharashtra'],
  ['Thane', 'Maharashtra'],
  ['Chennai', 'Tamil Nadu'],
  ['Coimbatore', 'Tamil Nadu'],
  ['Madurai', 'Tamil Nadu'],
  ['Tiruchirappalli', 'Tamil Nadu'],
  ['Salem', 'Tamil Nadu'],
  ['Hyderabad', 'Telangana'],
  ['Warangal', 'Telangana'],
  ['Visakhapatnam', 'Andhra Pradesh'],
  ['Vijayawada', 'Andhra Pradesh'],
  ['Tirupati', 'Andhra Pradesh'],
  ['Guntur', 'Andhra Pradesh'],
  ['Kochi', 'Kerala'],
  ['Thiruvananthapuram', 'Kerala'],
  ['Kozhikode', 'Kerala'],
  ['Thrissur', 'Kerala'],
  ['New Delhi', 'Delhi'],
  ['Gurugram', 'Haryana'],
  ['Faridabad', 'Haryana'],
  ['Noida', 'Uttar Pradesh'],
  ['Ghaziabad', 'Uttar Pradesh'],
  ['Lucknow', 'Uttar Pradesh'],
  ['Kanpur', 'Uttar Pradesh'],
  ['Varanasi', 'Uttar Pradesh'],
  ['Agra', 'Uttar Pradesh'],
  ['Prayagraj', 'Uttar Pradesh'],
  ['Kolkata', 'West Bengal'],
  ['Howrah', 'West Bengal'],
  ['Ahmedabad', 'Gujarat'],
  ['Surat', 'Gujarat'],
  ['Vadodara', 'Gujarat'],
  ['Rajkot', 'Gujarat'],
  ['Jaipur', 'Rajasthan'],
  ['Jodhpur', 'Rajasthan'],
  ['Udaipur', 'Rajasthan'],
  ['Kota', 'Rajasthan'],
  ['Bhopal', 'Madhya Pradesh'],
  ['Indore', 'Madhya Pradesh'],
  ['Gwalior', 'Madhya Pradesh'],
  ['Jabalpur', 'Madhya Pradesh'],
  ['Patna', 'Bihar'],
  ['Gaya', 'Bihar'],
  ['Ranchi', 'Jharkhand'],
  ['Jamshedpur', 'Jharkhand'],
  ['Bhubaneswar', 'Odisha'],
  ['Cuttack', 'Odisha'],
  ['Raipur', 'Chhattisgarh'],
  ['Guwahati', 'Assam'],
  ['Chandigarh', 'Chandigarh'],
  ['Ludhiana', 'Punjab'],
  ['Amritsar', 'Punjab'],
  ['Dehradun', 'Uttarakhand'],
  ['Shimla', 'Himachal Pradesh'],
  ['Srinagar', 'Jammu and Kashmir'],
  ['Jammu', 'Jammu and Kashmir'],
  ['Panaji', 'Goa'],
  ['Puducherry', 'Puducherry'],
];

export const COUNTRIES = [
  'India',
  'United States',
  'United Kingdom',
  'United Arab Emirates',
  'Singapore',
  'Australia',
  'Canada',
  'Germany',
  'Saudi Arabia',
  'Qatar',
  'Nepal',
  'Bangladesh',
  'Sri Lanka',
];

/** "Bengaluru, Karnataka" (a city suggestion) → city + state; plain text → just the city. */
export function splitCitySuggestion(value: string): { city: string; state: string | null } {
  const match = INDIAN_CITIES.find(([city, state]) => value === `${city}, ${state}`);
  return match ? { city: match[0], state: match[1] } : { city: value, state: null };
}

/** "+91 98765 43210" → ["+91", "98765 43210"]; a number without a code keeps +91. */
export function splitPhone(value: string): [string, string] {
  const m = /^(\+\d{1,4})\s*(.*)$/u.exec(value.trim());
  const code = m && COUNTRY_CODES.some(([c]) => c === m[1]) ? m[1]! : '+91';
  return [code, m ? m[2]! : value.trim()];
}
